# Generated by Django 5.1.1 on 2024-09-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_level', models.CharField(choices=[('Linux Engineer-L2', 'Linux Engineer-L2'), ('Linux Engineer-L3', 'Linux Engineer-L3'), ('Linux Engineer-L1', 'Linux Engineer-L1'), ('Windows Engineer-L2', 'Windows Engineer-L2'), ('Windows Engineer-L3', 'Windows Engineer-L3'), ('Windows Engineer-L1', 'Windows Engineer-L1'), ('Cloud Engineer - OCI Cloud-L2', 'Cloud Engineer - OCI Cloud-L2'), ('Cloud Engineer - OCI Cloud-L3', 'Cloud Engineer - OCI Cloud-L3'), ('Cloud Engineer - OCI Cloud-L1', 'Cloud Engineer - OCI Cloud-L1'), ('Storage/Backup-L3', 'Storage/Backup-L3'), ('Storage/Backup-L2', 'Storage/Backup-L2'), ('Storage/Backup-L1', 'Storage/Backup-L1'), ('Network Engineer-L3', 'Network Engineer-L3'), ('Network Engineer-L2', 'Network Engineer-L2'), ('Network Engineer-L1', 'Network Engineer-L1'), ('Terraform/IaaC Automation Engineer-L2', 'Terraform/IaaC Automation Engineer-L2'), ('Incident & Problem Manager-L2', 'Incident & Problem Manager-L2'), ('Change & Release Manager-L2', 'Change & Release Manager-L2'), ('RDBMS Admin-L2', 'RDBMS Admin-L2'), ('RDBMS Admin-L1', 'RDBMS Admin-L1'), ('RDBMS Admin-L3', 'RDBMS Admin-L3'), ('Non-RDBM Admin-L2', 'Non-RDBM Admin-L2'), ('Non-RDBM Admin-L1', 'Non-RDBM Admin-L1'), ('Non-RDBM Admin-L3', 'Non-RDBM Admin-L3'), ('Service Desk Lead-L2', 'Service Desk Lead-L2'), ('Monitoring/ Service Desk Engineer-L1', 'Monitoring/ Service Desk Engineer-L1'), ('Team Lead-L3', 'Team Lead-L3'), ('PMO-', 'PMO-'), ('Delivery Manager-', 'Delivery Manager-'), ('Delivery Head-', 'Delivery Head-'), ('Architect-', 'Architect-'), ('DR Manager-', 'DR Manager-'), ('Cloud Security-L3', 'Cloud Security-L3'), ('AD Engineer-L2', 'AD Engineer-L2'), ('AD Engineer-L3', 'AD Engineer-L3')], max_length=50)),
                ('hr_band', models.CharField(max_length=5)),
                ('experience_years', models.CharField(max_length=20)),
                ('responsibility_skills', models.TextField()),
                ('partner_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('airtel_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
