# Generated by Django 5.1.1 on 2024-09-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0002_ratecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratecard',
            name='experience_years',
            field=models.CharField(choices=[('1-3 years', '1-3 years'), ('3-5 years', '3-5 years'), ('5-8 years', '5-8 years')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ratecard',
            name='hr_band',
            field=models.CharField(choices=[('E2', 'E2'), ('E3', 'E3'), ('F', 'F')], max_length=5),
        ),
    ]
