# Generated by Django 5.1.1 on 2024-10-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0003_alter_ratecard_experience_years_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
        ),
    ]
