# Generated by Django 5.1.1 on 2024-10-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0005_auto_add_private_cloud_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scopingform',
            old_name='active_directory_count',
            new_name='Total_VMs_Devices',
        ),
        migrations.RenameField(
            model_name='scopingform',
            old_name='converged_platform',
            new_name='hyper_converged_platform_used',
        ),
        migrations.RenameField(
            model_name='scopingform',
            old_name='governance_support',
            new_name='ipc_management_in_scope',
        ),
        migrations.RenameField(
            model_name='scopingform',
            old_name='ipc_management',
            new_name='management_governance_support',
        ),
        migrations.RenameField(
            model_name='scopingform',
            old_name='linux_vm',
            new_name='no_of_ad_objects',
        ),
        migrations.RenameField(
            model_name='scopingform',
            old_name='network_devices',
            new_name='no_of_linux_vms',
        ),
        migrations.RenameField(
            model_name='scopingform',
            old_name='nosql_db',
            new_name='no_of_network_devices',
        ),
        migrations.RenameField(
            model_name='scopingform',
            old_name='private_cloud_hosts',
            new_name='no_of_nosql_dbs',
        ),
        migrations.RenameField(
            model_name='scopingform',
            old_name='rdbm_db',
            new_name='no_of_private_cloud_hosts',
        ),
        migrations.RenameField(
            model_name='scopingform',
            old_name='servers_for_dr',
            new_name='no_of_rdbms_dbs',
        ),
        migrations.RenameField(
            model_name='scopingform',
            old_name='windows_vm',
            new_name='no_of_servers_for_dr',
        ),
        migrations.RenameField(
            model_name='scopingform',
            old_name='storage_capacity',
            new_name='total_storage_capacity',
        ),
        migrations.RemoveField(
            model_name='ratecard',
            name='hr_band',
        ),
        migrations.RemoveField(
            model_name='ratecard',
            name='role_level',
        ),
        migrations.AddField(
            model_name='ratecard',
            name='role_hr_band',
            field=models.CharField(choices=[('Linux Engineer - F', 'Linux Engineer - F'), ('Linux Engineer - E2', 'Linux Engineer - E2'), ('Linux Engineer - E3', 'Linux Engineer - E3'), ('Windows Engineer - F', 'Windows Engineer - F'), ('Windows Engineer - E2', 'Windows Engineer - E2'), ('Windows Engineer - E3', 'Windows Engineer - E3'), ('Cloud Engineer - VMWare/Redhat - F', 'Cloud Engineer - VMWare/Redhat - F'), ('Cloud Engineer - VMWare/Redhat - E2', 'Cloud Engineer - VMWare/Redhat - E2'), ('Cloud Engineer - VMWare/Redhat - E3', 'Cloud Engineer - VMWare/Redhat - E3'), ('Storage/Backup - F', 'Storage/Backup - F'), ('Storage/Backup - E2', 'Storage/Backup - E2'), ('Storage/Backup - E3', 'Storage/Backup - E3'), ('Network Engineer - F', 'Network Engineer - F'), ('Network Engineer - E2', 'Network Engineer - E2'), ('Network Engineer - E3', 'Network Engineer - E3'), ('Terraform/IaaC Automation Engineer - E2', 'Terraform/IaaC Automation Engineer - E2'), ('Incident & Problem Manager - E2', 'Incident & Problem Manager - E2'), ('Change & Release Manager - E2', 'Change & Release Manager - E2'), ('RDBMS Admin - F', 'RDBMS Admin - F'), ('RDBMS Admin - E2', 'RDBMS Admin - E2'), ('RDBMS Admin - E3', 'RDBMS Admin - E3'), ('Non-RDBMS Admin - F', 'Non-RDBMS Admin - F'), ('Non-RDBMS Admin - E2', 'Non-RDBMS Admin - E2'), ('Non-RDBMS Admin - E3', 'Non-RDBMS Admin - E3'), ('Service Desk Lead - B', 'Service Desk Lead - B'), ('Monitoring/Service Desk Engineer - F', 'Monitoring/Service Desk Engineer - F'), ('Team Lead - E3', 'Team Lead - E3'), ('PMO - E2', 'PMO - E2'), ('Delivery Manager - E4', 'Delivery Manager - E4'), ('Delivery Head - E6', 'Delivery Head - E6'), ('Architect - E4', 'Architect - E4'), ('DR Manager - E2', 'DR Manager - E2'), ('Cloud Security - E3', 'Cloud Security - E3'), ('AD Admin - E2', 'AD Admin - E2'), ('AD Admin - E3', 'AD Admin - E3')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scopingform',
            name='no_of_windows_vms',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privatecloudprojectcost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='privatecloudprojectcost',
            name='kpi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privatecloudprojectcost',
            name='kpi_fte',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privatecloudprojectcost',
            name='support_window',
            field=models.CharField(choices=[('8x5', '8x5'), ('24x7', '24x7')], max_length=10),
        ),
        migrations.AlterField(
            model_name='privatecloudprojectcost',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
