# Generated by Django 5.1.1 on 2024-10-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0006_rename_active_directory_count_scopingform_total_vms_devices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatecloudprojectcost',
            name='complex',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='privatecloudprojectcost',
            name='kpi_fte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='privatecloudprojectcost',
            name='project_fte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='privatecloudprojectcost',
            name='project_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='privatecloudprojectcost',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='privatecloudprojectcost',
            name='total_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
