# Generated by Django 5.1.1 on 2024-10-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0009_add_level_to_ratecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratecard',
            name='experience_years',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ratecard',
            name='role_hr_band',
            field=models.CharField(max_length=50),
        ),
    ]
