# Generated by Django 5.1.1 on 2024-10-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0010_alter_ratecard_experience_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatecloudprojectcost',
            name='project_fte',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
