# Generated by Django 5.1.1 on 2024-10-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0012_autopopulate_ratecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivatePublicCloudProjectCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_level', models.CharField(max_length=100)),
                ('private_kpi', models.IntegerField(blank=True, null=True)),
                ('public_kpi', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('support_window', models.CharField(choices=[('8x5', '8x5'), ('24x7', '24x7')], max_length=10)),
                ('private_kpi_fte', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('public_kpi_fte', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('project_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('project_fte', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('complex', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.DeleteModel(
            name='PrivateCloudProjectCost',
        ),
    ]
