# Generated by Django 5.1.1 on 2024-10-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0013_privatepubliccloudprojectcost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatepubliccloudprojectcost',
            name='support_window',
            field=models.CharField(max_length=10),
        ),
    ]
