# Generated by Django 5.1.1 on 2024-11-02 13:10

from django.db import migrations, models
from decimal import Decimal

def add_initial_tools_data(apps, schema_editor):
    Tools = apps.get_model('Managed_services', 'Tools')

    initial_data = [
        {"function": "ITSM", "unit": "No of Resolvers", "rate_per_month": Decimal('3250.00')},
        {"function": "ITSM", "unit": "No of Devices", "rate_per_month": Decimal('220.00')},
        {"function": "Patching", "unit": "Servers", "rate_per_month": Decimal('162.00')},
        {"function": "ELK", "unit": "Servers", "rate_per_month": Decimal('200.00')},
    ]

    for data in initial_data:
        Tools.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0017_tools'),
    ]

    operations = [
       migrations.RunPython(add_initial_tools_data),
    ]
