# Generated by Django 5.1.1 on 2024-11-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0018_auto_fill_tools'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tools',
            new_name='Tool',
        ),
    ]
