# Generated by Django 5.1.1 on 2024-11-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0021_Cost_Calculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcalculation',
            name='cost_category',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='costcalculation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
