# Generated by Django 5.1.1 on 2024-11-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0022_alter_costcalculation_cost_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='rate_per_month',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tool',
            name='total_monthly',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
