# Generated by Django 5.1.1 on 2024-11-14 07:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0024_scopingform_description_scopingform_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('project_status', models.CharField(max_length=50)),
                ('contract_duration', models.IntegerField()),
                ('resource_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tools', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('oncall', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('travel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('penalty_risk', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
    ]
