# Generated by Django 5.1.1 on 2024-11-15 07:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0025_costsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyCostSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('y1', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('y2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('y3', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('y4', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('y5', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
    ]
