# Generated by Django 5.1.1 on 2024-11-25 06:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0026_yearlycostsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectResourceUtilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('Linux_Engineer_F', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Linux_Engineer_E2', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Linux_Engineer_E3', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Windows_Engineer_F', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Windows_Engineer_E2', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Windows_Engineer_E3', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Cloud_Engineer_VMWare_Redhat_F', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Cloud_Engineer_VMWare_Redhat_E2', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Cloud_Engineer_VMWare_Redhat_E3', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Storage_Backup_F', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Storage_Backup_E2', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Storage_Backup_E3', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Network_Engineer_F', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Network_Engineer_E2', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Network_Engineer_E3', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Terraform_IaaC_Automation_Engineer_E2', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Incident_Problem_Manager_E2', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Change_Release_Manager_E2', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('RDBMS_Admin_E2', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('RDBMS_Admin_E3', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Non_RDBMS_Admin_E2', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Non_RDBMS_Admin_E3', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('AD_Admin_E2', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('AD_Admin_E3', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Service_Desk_Lead_B', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Monitoring_Service_Desk_Engineer_F', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Team_Lead_E3', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('PMO_E2', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Delivery_Manager_E4', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Delivery_Head_E6', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('Architect_E4', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
                ('DR_Manager_E2', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10)),
            ],
        ),
    ]
