# Generated by Django 5.1.1 on 2024-11-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0027_projectresourceutilisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectresourceutilisation',
            old_name='Cloud_Engineer_VMWare_Redhat_E2',
            new_name='Cloud_Engineer_OCI_Cloud_E2',
        ),
        migrations.RenameField(
            model_name='projectresourceutilisation',
            old_name='Cloud_Engineer_VMWare_Redhat_E3',
            new_name='Cloud_Engineer_OCI_Cloud_E3',
        ),
        migrations.RenameField(
            model_name='projectresourceutilisation',
            old_name='Cloud_Engineer_VMWare_Redhat_F',
            new_name='Cloud_Engineer_OCI_Cloud_F',
        ),
    ]
