# Generated by Django 5.1.1 on 2024-11-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0030_autofill_rateCard_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='costsummary',
            name='project_name',
            field=models.CharField(default='Not available', max_length=255),
        ),
        migrations.AddField(
            model_name='projectresourceutilisation',
            name='project_name',
            field=models.CharField(default='Not available', max_length=255),
        ),
        migrations.AddField(
            model_name='yearlycostsummary',
            name='project_name',
            field=models.CharField(default='Not available', max_length=255),
        ),
    ]
