# Generated by Django 5.1.1 on 2024-11-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0031_costsummary_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopingform',
            name='project_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
