# Generated by Django 5.1.1 on 2024-12-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0033_costcalculation_y10_costcalculation_y6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopingform',
            name='product_name',
            field=models.CharField(choices=[('Cloud Re-sale', 'Cloud Re-sale'), ('IBM new', 'IBM new'), ('Airtel Cloud', 'Airtel Cloud'), ('Exisiting Cloud-Domestic', 'Exisiting Cloud-Domestic'), ('GDCH', 'GDCH'), ('Exisiting Cloud-Nxtra', 'Exisiting Cloud-Nxtra'), ('MS Licence-Nxtra', 'MS Licence-Nxtra')], default='No product_name provided', max_length=30),
        ),
    ]
