# Generated by Django 5.1.1 on 2024-12-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0034_scopingform_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopingform',
            name='SA_name',
            field=models.CharField(default='Not Assigned', max_length=255),
        ),
        migrations.AlterField(
            model_name='scopingform',
            name='product_name',
            field=models.CharField(choices=[('Cloud_Re_sale', 'Cloud_Re_sale'), ('IBM_new', 'IBM_new'), ('Airtel_Cloud', 'Airtel_Cloud'), ('Exisiting_Cloud_Domestic', 'Exisiting_Cloud_Domestic'), ('GDCH', 'GDCH'), ('Exisiting_Cloud_Nxtra', 'Exisiting_Cloud_Nxtra'), ('MS_Licence_Nxtra', 'MS_Licence_Nxtra')], default='No product_name provided', max_length=30),
        ),
    ]
