# Generated by Django 5.1.1 on 2024-12-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managed_services', '0037_costsummary_sa_name_costsummary_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresourceutilisation',
            name='project_status',
            field=models.CharField(default='No project_status provided', max_length=50),
        ),
        migrations.AddField(
            model_name='yearlycostsummary',
            name='project_status',
            field=models.CharField(default='No project_status provided', max_length=50),
        ),
        migrations.AlterField(
            model_name='scopingform',
            name='project_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed'), ('Dropped', 'Dropped'), ('Hold', 'Hold'), ('Lost', 'Lost'), ('Passive', 'Passive'), ('Submitted', 'Submitted'), ('Won', 'Won')], max_length=50),
        ),
    ]
